[package]
name = "filament-safe"
version = "0.1.0"
edition = "2021"

[features]
default = ["prebuilt"]
prebuilt = ["filament-bindings/prebuilt"]

[dependencies]
filament-bindings = { path = "../filament-bindings", default-features = false }
bitflags = "1.3"
num_enum = "0.5.6"