[package]
name = "filament-sys"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[build-dependencies]
bindgen = "0.59"
cmake = "0.1"
serde_json = "1.0"
tar = "0.4"
serde = { version = "1.0", features = ["derive"] }
flate2 = "1.0"
ureq = "2.4"