name: filament-bindings Build Release
on:
  push:
    tags:
      - filament-bindings/v*
jobs:
  create-release:
    runs-on: 'ubuntu-20.04'
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBody: true
          prerelease: true
          draft: true
          token: ${{ secrets.ACCESS_TOKEN }}
          owner: EYHN
          repo: filament-binaries
  build:
    runs-on: ${{ matrix.target.os }}
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: ubuntu-20.04
            triple: x86_64-unknown-linux-gnu
          - os: macos-11
            triple: x86_64-apple-darwin
          - os: macos-11
            triple: aarch64-apple-darwin
          - os: windows-2019
            triple: x86_64-pc-windows-msvc
        features: ["default"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialize Submodules
        run: |
          git submodule update --init --depth 1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install libglu1-mesa-dev ninja-build libxi-dev libc++-11-dev libc++abi-11-dev
          df -h
      - name: Install LLVM (Windows) # required for bindgen to work, see https://github.com/rust-lang/rust-bindgen/issues/1797
        uses: KyleMayes/install-llvm-action@v1
        if: runner.os == 'Windows'
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
      - name: Set LIBCLANG_PATH (Windows)
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
        if: runner.os == 'Windows'
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install ninja
      - name: Install Rust target ${{ matrix.target.triple }}
        run: |
          rustup target add ${{ matrix.target.triple }}
      - name: Build ${{ matrix.target.triple }}
        env:
          FILAMENT_BUILD_CACHE_DIR: ${{ runner.temp }}/release
          FILAMENT_BUILD_OUT_DIR: ${{ runner.temp }}/out
          FILAMENT_BUILD_DISABLE_CACHE: ON
        run: |
          cargo build -vv --release -p filament-bindings --features ${{ matrix.features }} --target ${{ matrix.target.triple }}
      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ runner.temp }}/release/*
          artifactContentType: application/gzip
          artifactErrorsFailBuild: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          draft: true
          token: ${{ secrets.ACCESS_TOKEN }}
          owner: EYHN
          repo: filament-binaries
